USE TRABALHOSBD2;

Delete FROM TABELADEPRECOS;
Delete FROM STOCKARMAZEM;
Delete FROM STOCKDAMAQUINADEVENDA;
Delete FROM STOCKDAVIATURA;
Delete FROM QUANTIDADEDEVENDA;
Delete FROM ASSISTENCIA;
Delete FROM FORNECIMENTO;
Delete FROM MAQUINADEVENDA;
Delete FROM PONTODEVENDA;
Delete FROM LOTE;
Delete FROM CONDUTOR;
Delete FROM FUNCIONARIO;
Delete FROM PRODUTO;
Delete FROM LOCALDEVENDA;
Delete FROM FORNECEDOR;
Delete FROM ARMAZEM;
Delete FROM VIATURA;
Delete FROM REGIAO;
Delete FROM PAIS;


DROP TABLE TABELADEPRECOS;
DROP TABLE STOCKARMAZEM;
DROP TABLE STOCKDAMAQUINADEVENDA;
DROP TABLE STOCKDAVIATURA;
DROP TABLE QUANTIDADEDEVENDA;
DROP TABLE ASSISTENCIA;
DROP TABLE FORNECIMENTO;
DROP TABLE MAQUINADEVENDA;
DROP TABLE PONTODEVENDA;
DROP TABLE LOTE;
DROP TABLE CONDUTOR;
DROP TABLE FUNCIONARIO;
DROP TABLE PRODUTO;
DROP TABLE LOCALDEVENDA;
DROP TABLE FORNECEDOR;
DROP TABLE ARMAZEM;
DROP TABLE VIATURA;
DROP TABLE REGIAO;
DROP TABLE PAIS;

